### ISSUE TITLE
ImportError: No module named git

### ISSUE THREAD

**Issue by jrivard** [dxa4481/truffleHog#4]
Running on OpenSUSE Leap 42.2.

pip install -r requirements.txt 
> Requirement already satisfied: GitPython==2.1.1 in /usr/lib/python3.4/site-packages (from -r requirements.txt (line 1))
> Requirement already satisfied: gitdb2>=2.0.0 in /usr/lib/python3.4/site-packages (from GitPython==2.1.1->-r requirements.txt (line 1))
> Requirement already satisfied: smmap2>=2.0.0 in /usr/lib/python3.4/site-packages (from gitdb2>=2.0.0->GitPython==2.1.1->-r requirements.txt (line 1))

python truffleHog.py https://github.com/dxa4481/truffleHog.git
> Traceback (most recent call last):
>  File "truffleHog.py", line 2, in <module>
>    from git import Repo
>ImportError: No module named git

**Comment by sseering** [comment]
see https://github.com/dxa4481/truffleHog/issues/3

**Comment by dxa4481** [comment]
It looks like your dependancies aren't getting installed correctly for the version of python you're using. Make sure the version of pip and python are aligned, then you can also try uninstalling GitPython and reinstalling it.

**Comment by jrivard** [comment]
Bummer, guess one needs to know how to manage the python runtime to get this working.  I don't so I give up for now.

**Comment by rupsray** [comment]
@jrivard to check both Python and pip are aligned check their versions.
![python pip alignment](https://user-images.githubusercontent.com/2688624/39698269-d3dbaf94-5211-11e8-972f-70ea0decab37.JPG)
As you can see in the above image, pip and python3 are pointing to the same version for me. So I have to use **python3** instead of **python** while performing truffleHog scan. Check this [document](https://dzone.com/articles/cloud-security-best-practices-finding-securing-and) for installation.

**Comment by dxa4481** [comment]
If nothing else you can try the docker container
