### ISSUE TITLE
Depth limits are needed to prevent long jobs

### ISSUE THREAD

**Issue by dend** [dxa4481/truffleHog#64]
When leveraging `trufflehog` for repo scans, it would be helpful to introduce the concept of depth limits, to ensure that when a scan is performed, it only goes to a certain number of commits back. On a test repository that I have, there is a huge number of commits dating back to 2014, and the job is running well more than 24 hours to go deep across all of them.

**Comment by dxa4481** [comment]
I've added two flags to help with this

```
  --since_commit SINCE_COMMIT
                        Only scan from a given commit hash
  --max_depth MAX_DEPTH
                        The max commit depth to go back when searching for
                        secrets
```

**Comment by BillBrower** [comment]
@dxa4481 If I were to use `--max_depth 1` would that limit `trufflehog` to the most recent commit?

**Comment by calve** [comment]
Hi @dxa4481 ; can you elaborate on how `since_commit` is supposed to work ?

More specificaly; what one should expect when ``since_commit` is not in the current branch ? It looks like trufflehog switch between all branches found, and some might not contains the specified commit (thinking of a pull request for example)

**Comment by dxa4481** [comment]
@BillBrower That's the expected behavior

@calve `since_commit` is sort of like the commit depth flag, the scanner will scan backwards in time until it encounters the commit hash in question, and then it will stop scanning. If it does not find the hash, it will scan the entire branch.

**Comment by calve** [comment]
Thanks @dxa4481. I'm looking to implement an option to audit a single commit range; my use case is to scan only new commits in a CI pipeline. The current architecture makes it a bit difficult as responsabilities are not clearly defined in the code; the same function compute diffs, pass it to filters, print issues, etc ...

I'm going to split responsabilities and clean up before implementing some kind of a ``--range HEAD..123456` `. In the meantime, any chance you address the issue/PR opened here ? I'm willing to help you if needed.

**Comment by BillBrower** [comment]
@calve If you're only scanning new commits couldn't you just run trufflehog with `--max_depth 1` in your CI pipeline everytime a commit is pushed?

**Comment by calve** [comment]
@BillBrower one can push more than one commit. Sure I could compute the number of commit between HEAD and `$branch_root` and pass it to `--max_depth` but I find it somewhat hacky

**Comment by dxa4481** [comment]
There's a few features that I think might be nice.

It would be nice if you could pass TH a list of scanned commits, so that it can scan back in time and break as soon as it sees a commit it's previously scanned. This is preferable over the current implementation because currently you can only give it one hash, but this doesn't work nicely if you only remember the last commit and then someone does a rebase.

Another nice feature would be the ability to clone only a range of commit history. Currently the entire history is cloned and for big repos the actual cloning becomes the bottleneck. I think there's a feature in git to do this. I know you can pass it a depth flag... not sure what else you can do regarding ranges and commit hashes.

Lastly the command line options are getting a little out of control. I've been saying for a while now, I need to support an option to pull settings out into a json configuration file. One of the open PR's (path regexes) are actually blocked on this feature.

Let me know what your thoughts are. Don't do it all in one PR, make sure it's split up. I'm quicker to merge in smaller code changes.

**Comment by calve** [comment]
> Another nice feature would be the ability to clone only a range of commit history. Currently the entire history is cloned and for big repos the actual cloning becomes the bottleneck.

I'm not sure if git can do partial clones, but maybe bare repositories can help ? Not my priority atm but I'll look into it

> I've been saying for a while now, I need to support an option to pull settings out into a json configuration file.

You might want to consider yaml (which is a subset of json, so json is still an option). I aggree that regexs should not be hardcoded in python files, but read from external files (and TF should provide a default set as today). That would make it safier for users to PR their regexs.

> Let me know what your thoughts are.

In an ideal world I would

 1. flake8 all the things ;)
 2. write tests (cant found any, am I missing them ?)
 3. factorise

**Comment by dxa4481** [comment]
The tests are here https://github.com/dxa4481/truffleHog/blob/master/test_all.py

code coverage is kind of weak, but I think travis runs them every time you push. Looks like your recent PR actually failed the travis build

**Comment by calve** [comment]
Indeed, should be ok by now
