### ISSUE TITLE
Regex matching functionality is still broken in the new patch

### ISSUE THREAD

**Issue by anshumanbh** [dxa4481/truffleHog#75]
The new patch actually is not finding any secrets. Can you try running truffleHog on this repo - https://github.com/secretuser1/secretrepo.git. It is not finding the Slack tokens along with the AWS secrets here - https://github.com/secretuser1/secretrepo/blob/master/secretfile.txt#L2

Am I missing something?

Also, if I wanted to have my own regex file, am I supposed to just overwrite it and start trufflehog or am I supposed to run some setup script? I am very confused.

The command I ran after git cloning the repo was - python truffleHog/truffleHog.py --regex --entropy=False https://github.com/secretuser1/secretrepo.git. And, there was no output.

@milo-minderbinder @dxa4481 @carnal0wnage

**Comment by anshumanbh** [comment]
I can also confirm that the patch by @milo-minderbinder here - https://github.com/dxa4481/truffleHog/pull/71 fixes this bug.

**Comment by dxa4481** [comment]
The previous patch was actually working as expected, trufflehog was reporting no results because of another patch that had an unexpected result. I set the depth limit to commits, and the gitpython documentation said defaulting this to None would mean no depth limit, however in practice it meant set the depth limit to 0.

I've pushed a temporary work around by settting the default depth limit to 1,000,000 commits. https://github.com/dxa4481/truffleHog/blob/master/truffleHog/truffleHog.py#L25

This is a little hacky, but it works for now.

Regarding the question of moving rules from the python file into a yaml file, please open another issue for that. Closing this now because everything seems to be working as expected with my latest push.
