### ISSUE TITLE
JSON output format

### ISSUE THREAD

**Issue by jt-mott** [dxa4481/truffleHog#95]
The current JSON output format has no commas between each identified password/secret object and the objects are not organized into an array of objects.  This is not parsed well by native json parsing libraries such as Python's json library.  Would it be reasonable to format the JSON output as an array of comma separated password/secret instance objects?

**Comment by dxa4481** [comment]
Sure, I'll remove the [`indent=4`](https://github.com/dxa4481/truffleHog/blob/master/truffleHog/truffleHog.py#L128) which I think adds the new lines. If you're using this for python though, I suggest just importing truffleHog as a library and using the dictionary returned, rather than parsing the JSON output.

**Comment by rrupesh** [comment]
Hi. I am still unable to get a valid JSON output as an array.. Can you suggest a way to get a valid JSON output?

**Comment by zioalex** [comment]
Hi @rrupesh  I used this small python script:
```python
import json

# Open the file and read the lines
with open('./output/trufflehog_analysis.json', 'r') as f:
    lines = f.readlines()

# Create a new JSON object
unique_json_object = {}

# Add each JSON object to the new JSON object as a property
for i, line in enumerate(lines):
    unique_json_object[f'object{i+1}'] = json.loads(line)

# Print the unique JSON object
print(json.dumps(unique_json_object, indent=4))
```
